#pragma once

// AUTO-GENERATED by WaratahCmd.exe (https://github.com/microsoft/hidtools)

// HID Usage Tables: 1.7.0
// Descriptor size: 265 (bytes)
// +----------+---------+-------------------+
// | ReportId | Kind    | ReportSizeInBytes |
// +----------+---------+-------------------+
// |       64 | Feature |                 1 |
// +----------+---------+-------------------+
// |       65 | Feature |                 1 |
// +----------+---------+-------------------+
// |       66 | Feature |                15 |
// +----------+---------+-------------------+
// |       67 | Output  |                 7 |
// +----------+---------+-------------------+
static const uint8_t hidReportDescriptor[] = 
{
    0x05, 0x0D,          // UsagePage(Digitizers[0x000D])
    0x09, 0x05,          // UsageId(Touch Pad[0x0005])
    0xA1, 0x01,          // Collection(Application)
    0x85, 0x40,          //     ReportId(64)
    0x05, 0x0D,          //     UsagePage(Digitizers[0x000D])
    0x09, 0xB0,          //     UsageId(Button Press Threshold[0x00B0])
    0x35, 0x6E,          //     PhysicalMinimum(110)
    0x46, 0xBE, 0x00,    //     PhysicalMaximum(190)
    0x66, 0x01, 0x01,    //     Unit('gram', SiLinear, Gram:1)
    0x55, 0x00,          //     UnitExponent(1)
    0x15, 0x01,          //     LogicalMinimum(1)
    0x25, 0x03,          //     LogicalMaximum(3)
    0x95, 0x01,          //     ReportCount(1)
    0x75, 0x08,          //     ReportSize(8)
    0xB1, 0x02,          //     Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0x85, 0x41,          //     ReportId(65)
    0x05, 0x0E,          //     UsagePage(Haptics[0x000E])
    0x09, 0x01,          //     UsageId(Simple Haptic Controller[0x0001])
    0xA1, 0x02,          //     Collection(Logical)
    0x05, 0x0E,          //         UsagePage(Haptics[0x000E])
    0x09, 0x23,          //         UsageId(Intensity[0x0023])
    0x35, 0x00,          //         PhysicalMinimum(0)
    0x45, 0x00,          //         PhysicalMaximum(0)
    0x65, 0x00,          //         Unit(None)
    0x55, 0x00,          //         UnitExponent(1)
    0x15, 0x00,          //         LogicalMinimum(0)
    0x25, 0x04,          //         LogicalMaximum(4)
    0x95, 0x01,          //         ReportCount(1)
    0x75, 0x08,          //         ReportSize(8)
    0xB1, 0x02,          //         Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0xC0,                //     EndCollection()
    0x85, 0x42,          //     ReportId(66)
    0x05, 0x0E,          //     UsagePage(Haptics[0x000E])
    0x09, 0x01,          //     UsageId(Simple Haptic Controller[0x0001])
    0xA1, 0x02,          //     Collection(Logical)
    0x05, 0x0E,          //         UsagePage(Haptics[0x000E])
    0x09, 0x10,          //         UsageId(Waveform List[0x0010])
    0xA1, 0x02,          //         Collection(Logical)
    0x05, 0x0A,          //             UsagePage(Ordinal[0x000A])
    0x19, 0x03,          //             UsageIdMin(Instance 3[0x0003])
    0x29, 0x07,          //             UsageIdMax(Instance 7[0x0007])
    0x35, 0x00,          //             PhysicalMinimum(0)
    0x45, 0x00,          //             PhysicalMaximum(0)
    0x65, 0x00,          //             Unit(None)
    0x55, 0x00,          //             UnitExponent(1)
    0x16, 0x01, 0x10,    //             LogicalMinimum(4,097)
    0x26, 0xFF, 0x2F,    //             LogicalMaximum(12,287)
    0x95, 0x05,          //             ReportCount(5)
    0x75, 0x10,          //             ReportSize(16)
    0xB1, 0x02,          //             Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0xC0,                //         EndCollection()
    0x05, 0x0E,          //         UsagePage(Haptics[0x000E])
    0x09, 0x11,          //         UsageId(Duration List[0x0011])
    0xA1, 0x02,          //         Collection(Logical)
    0x05, 0x0A,          //             UsagePage(Ordinal[0x000A])
    0x19, 0x03,          //             UsageIdMin(Instance 3[0x0003])
    0x29, 0x07,          //             UsageIdMax(Instance 7[0x0007])
    0x35, 0x00,          //             PhysicalMinimum(0)
    0x45, 0x32,          //             PhysicalMaximum(50)
    0x66, 0x01, 0x10,    //             Unit('millisecond', SiLinear, Seconds:1)
    0x55, 0x0D,          //             UnitExponent(0.001)
    0x15, 0x00,          //             LogicalMinimum(0)
    0x25, 0x32,          //             LogicalMaximum(50)
    0x95, 0x05,          //             ReportCount(5)
    0x75, 0x08,          //             ReportSize(8)
    0xB1, 0x02,          //             Feature(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0xC0,                //         EndCollection()
    0xC0,                //     EndCollection()
    0x85, 0x43,          //     ReportId(67)
    0x05, 0x0E,          //     UsagePage(Haptics[0x000E])
    0x09, 0x01,          //     UsageId(Simple Haptic Controller[0x0001])
    0xA1, 0x02,          //     Collection(Logical)
    0x05, 0x0E,          //         UsagePage(Haptics[0x000E])
    0x09, 0x21,          //         UsageId(Manual Trigger[0x0021])
    0x35, 0x00,          //         PhysicalMinimum(0)
    0x45, 0x00,          //         PhysicalMaximum(0)
    0x65, 0x00,          //         Unit(None)
    0x55, 0x00,          //         UnitExponent(1)
    0x15, 0x01,          //         LogicalMinimum(1)
    0x25, 0x07,          //         LogicalMaximum(7)
    0x95, 0x01,          //         ReportCount(1)
    0x75, 0x08,          //         ReportSize(8)
    0x91, 0x02,          //         Output(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0x05, 0x0E,          //         UsagePage(Haptics[0x000E])
    0x09, 0x23,          //         UsageId(Intensity[0x0023])
    0x35, 0x00,          //         PhysicalMinimum(0)
    0x45, 0x00,          //         PhysicalMaximum(0)
    0x65, 0x00,          //         Unit(None)
    0x55, 0x00,          //         UnitExponent(1)
    0x15, 0x00,          //         LogicalMinimum(0)
    0x25, 0x04,          //         LogicalMaximum(4)
    0x95, 0x01,          //         ReportCount(1)
    0x75, 0x08,          //         ReportSize(8)
    0x91, 0x02,          //         Output(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0x05, 0x0E,          //         UsagePage(Haptics[0x000E])
    0x09, 0x24,          //         UsageId(Repeat Count[0x0024])
    0x35, 0x00,          //         PhysicalMinimum(0)
    0x45, 0x00,          //         PhysicalMaximum(0)
    0x65, 0x00,          //         Unit(None)
    0x55, 0x00,          //         UnitExponent(1)
    0x15, 0x00,          //         LogicalMinimum(0)
    0x25, 0x05,          //         LogicalMaximum(5)
    0x95, 0x01,          //         ReportCount(1)
    0x75, 0x08,          //         ReportSize(8)
    0x91, 0x02,          //         Output(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0x05, 0x0E,          //         UsagePage(Haptics[0x000E])
    0x09, 0x25,          //         UsageId(Retrigger Period[0x0025])
    0x35, 0x00,          //         PhysicalMinimum(0)
    0x46, 0xE8, 0x03,    //         PhysicalMaximum(1,000)
    0x66, 0x01, 0x10,    //         Unit('millisecond', SiLinear, Seconds:1)
    0x55, 0x0D,          //         UnitExponent(0.001)
    0x15, 0x00,          //         LogicalMinimum(0)
    0x26, 0xE8, 0x03,    //         LogicalMaximum(1,000)
    0x95, 0x01,          //         ReportCount(1)
    0x75, 0x10,          //         ReportSize(16)
    0x91, 0x02,          //         Output(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0x05, 0x0E,          //         UsagePage(Haptics[0x000E])
    0x09, 0x28,          //         UsageId(Waveform Cutoff Time[0x0028])
    0x36, 0xE8, 0x03,    //         PhysicalMinimum(1,000)
    0x46, 0x88, 0x13,    //         PhysicalMaximum(5,000)
    0x66, 0x01, 0x10,    //         Unit('millisecond', SiLinear, Seconds:1)
    0x55, 0x0D,          //         UnitExponent(0.001)
    0x16, 0xE8, 0x03,    //         LogicalMinimum(1,000)
    0x26, 0x88, 0x13,    //         LogicalMaximum(5,000)
    0x95, 0x01,          //         ReportCount(1)
    0x75, 0x10,          //         ReportSize(16)
    0x91, 0x02,          //         Output(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, NonVolatile, BitField)
    0xC0,                //     EndCollection()
    0xC0,                // EndCollection()
};

#pragma pack(push,1)

#define HID_REPORT_FEATURE64_ID (64)
struct HidReportFeature64
{
    uint8_t ReportId = HID_REPORT_FEATURE64_ID;
    uint8_t ButtonPressThreshold;
};

#define HID_REPORT_FEATURE65_ID (65)
struct HidReportFeature65
{
    uint8_t ReportId = HID_REPORT_FEATURE65_ID;
    uint8_t Intensity;
};

#define HID_REPORT_FEATURE66_ID (66)
struct HidReportFeature66
{
    uint8_t ReportId = HID_REPORT_FEATURE66_ID;
    uint16_t Instance3;
    uint16_t Instance4;
    uint16_t Instance5;
    uint16_t Instance6;
    uint16_t Instance7;
    uint8_t Instance31;
    uint8_t Instance41;
    uint8_t Instance51;
    uint8_t Instance61;
    uint8_t Instance71;
};

#define HID_REPORT_OUTPUT67_ID (67)
struct HidReportOutput67
{
    uint8_t ReportId = HID_REPORT_OUTPUT67_ID;
    uint8_t ManualTrigger;
    uint8_t Intensity;
    uint8_t RepeatCount;
    uint16_t RetriggerPeriod;
    uint16_t WaveformCutoffTime;
};

#pragma pack(pop)