#pragma once
/* Generated by knuckle_training/train.py; do not hand-edit.
 * Experimental: calibration data is not a generalization guarantee. */
#define KNUCKLE_MODEL_VERSION 1
#define KNUCKLE_MODEL_EXPERIMENTAL 1
#define KNUCKLE_MODEL_CONTACTS 5
#define KNUCKLE_MODEL_SHA256 "826103c8e8d6ee48b04831f6297c9a73e79add6d5b5802ff526ba41f440ab7aa"
typedef struct { float weight[2], bias, low[2], high[2]; } knuckle_model_head_t;
static const knuckle_model_head_t knuckle_model_onset = {
    {-0.096841459f, -0.117875052f}, 7.69645693f, {33.8178714f, 0.0f}, {60.1821286f, 20.8f} };
static const knuckle_model_head_t knuckle_model_complete = {
    {-0.100177511f, -0.0988264205f}, 7.82492913f, {36.4241631f, 0.839346197f}, {61.5758369f, 22.3710578f} };
