#pragma once
#include "SYS/aux_output.h"
#define usb_aux_active aux_output_active
#define usb_aux_cancel aux_output_cancel
#define usb_aux_complete aux_output_complete
#define usb_aux_neutral_pending aux_output_neutral_pending
#define usb_aux_release_pending aux_output_release_pending
#define usb_aux_report_current aux_output_report_current
#define usb_aux_report_t aux_output_report_t
#define usb_aux_reset aux_output_reset
#define usb_aux_resume aux_output_resume
#define usb_aux_steps aux_output_steps
#define usb_aux_take aux_output_take
#define usb_aux_unsubmitted aux_output_unsubmitted
