/**
 * @file cs40l25_sym.h
 *
 * @brief Generic firmware symbol aliases for the active CS40L25 firmware image
 */

#ifndef CS40L25_CONFIG_SYM_H
#define CS40L25_CONFIG_SYM_H

#ifdef __cplusplus
extern "C" {
#endif

#include "I2C/SUB_DEV/mcu-drivers/cs40l25/cs40l25_sym.h"

/***********************************************************************************************************************
 * LITERALS & CONSTANTS
 **********************************************************************************************************************/

/**
 * @defgroup CS40L25_ALGORITHMS
 * @brief Defines indicating presence of HALO Core Algorithms
 *
 * These aliases keep the driver source generic while binding it to the
 * currently generated ext-boost firmware symbol table.
 *
 * @{
 */
#define CS40L25_ALGORITHM_FIRMWARE
#define CS40L25_ALGORITHM_VIBEGEN
#define CS40L25_ALGORITHM_DYNAMIC_F0
/** @} */

/**
 * @defgroup CS40L25_SYM_
 * @brief Generic aliases for firmware controls used by the driver
 *
 * @{
 */
#define CS40L25_SYM_FIRMWARE_HALO_STATE \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_HALO_STATE
#define CS40L25_SYM_FIRMWARE_HALO_HEARTBEAT \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_HALO_HEARTBEAT
#define CS40L25_SYM_FIRMWARE_EVENTCONTROL \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_EVENTCONTROL
#define CS40L25_SYM_FIRMWARE_GPIO1EVENT \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_GPIO1EVENT
#define CS40L25_SYM_FIRMWARE_GPIO2EVENT \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_GPIO2EVENT
#define CS40L25_SYM_FIRMWARE_GPIO3EVENT \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_GPIO3EVENT
#define CS40L25_SYM_FIRMWARE_GPIO4EVENT \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_GPIO4EVENT
#define CS40L25_SYM_FIRMWARE_GPIOPLAYBACKEVENT \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_GPIOPLAYBACKEVENT
#define CS40L25_SYM_FIRMWARE_TRIGGERPLAYBACKEVENT \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_TRIGGERPLAYBACKEVENT
#define CS40L25_SYM_FIRMWARE_RXREADYEVENT \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_RXREADYEVENT
#define CS40L25_SYM_FIRMWARE_ACTIVETOSTANDBYEVENT \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_ACTIVETOSTANDBYEVENT
#define CS40L25_SYM_FIRMWARE_HARDWAREEVENT \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_HARDWAREEVENT
#define CS40L25_SYM_FIRMWARE_INDEXBUTTONPRESS \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_INDEXBUTTONPRESS
#define CS40L25_SYM_FIRMWARE_INDEXBUTTONRELEASE \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_INDEXBUTTONRELEASE
#define CS40L25_SYM_FIRMWARE_GPIO_BUTTONDETECT \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_GPIO_BUTTONDETECT
#define CS40L25_SYM_FIRMWARE_GAIN_CONTROL \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_GAIN_CONTROL
#define CS40L25_SYM_FIRMWARE_GPIO_ENABLE \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_GPIO_ENABLE
#define CS40L25_SYM_FIRMWARE_POWERSTATE \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_POWERSTATE
#define CS40L25_SYM_FIRMWARE_POWERONSEQUENCE \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_POWERONSEQUENCE
#define CS40L25_SYM_FIRMWARE_USER_CONTROL_IPDATA \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_USER_CONTROL_IPDATA
#define CS40L25_SYM_FIRMWARE_USER_CONTROL_RESPONSE \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_USER_CONTROL_RESPONSE
#define CS40L25_SYM_FIRMWARE_F0_STORED \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_F0_STORED
#define CS40L25_SYM_FIRMWARE_REDC_STORED \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_REDC_STORED
#define CS40L25_SYM_FIRMWARE_IRQMASKSEQUENCE \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_IRQMASKSEQUENCE
#define CS40L25_SYM_FIRMWARE_IRQMASKSEQUENCE_VALID \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_IRQMASKSEQUENCE_VALID
#define CS40L25_SYM_FIRMWARE_Q_STORED \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_Q_STORED
#define CS40L25_SYM_FIRMWARE_FEATURE_BITMAP \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_FEATURE_BITMAP
#define CS40L25_SYM_FIRMWARE_USE_EXT_BOOST \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_USE_EXT_BOOST
#define CS40L25_SYM_FIRMWARE_GPI_PLAYBACK_DELAY \
    CS40L25_SYM_FIRMWARE_PRINCE_HAPCTRL_RAM_REMAP_EXT_BOOST_GPI_PLAYBACK_DELAY

/** @} */

/**********************************************************************************************************************/
#ifdef __cplusplus
}
#endif

#endif // CS40L25_CONFIG_SYM_H
